version: '3.1'

#  定义服务
services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  web:
    image: nginx
    ports:
      - "9000:9000"
      - "80:80"
    volumes:
      - ./nginx-mac.conf:/etc/nginx/conf.d/default.conf
volumes:
  db-data:
networks:
  backend:  
